; PlatformIO Project Configuration File
;

[platformio]
default_envs = m5stamp-3cu
[env:m5stamp-3cu]
platform = espressif32 
board = m5stamp-3cu
framework = arduino
monitor_speed = 115200
upload_speed = 921600
#upload_speed  = 115200
lib_extra_dirs = ../___MeLib

; Set CPU Watchdog-Timeout to 1 s
build_flags =
  -D CONFIG_ESP_INT_WDT_TIMEOUT_MS=1500 

; Schaltet die vollständige Erkennung für verschachtelte Bibliotheken frei:
;lib_ldf_mode = deep+
;lib_ldf_mode = chain+
; Dieser Befehl zwingt den Compiler, Ihren gesamten Ordner blind zu durchsuchen:
;build_flags = -I../___MeLib


;upload_protocol = esptool
; Add one of the following lines for OTA partitions on ESP32
;upload_port  =  192.168.167.52       ; Either use the IP address:
                                    ; Or use the hostname (default is usually 'esp32-[chipID]')
                                    ; You can set a custom hostname in your code (see below)
                                    ; upload_port = your_device_hostname.local
;board_build.partitions = default_ota.csv  ; Default with OTA support
;board_build.partitions = partitions/minimal_ota.csv  ; Minimal with OTA support (more space for sketch
;upload_protocol = espota
;upload_port  =  staticIP
;upload_flags =
;  --port=3232
;  --debug
;  --timeout=65
;  --auth=admin
;  --host_ip=192.168.167.253
;  --host_port=12345
